services:
  postgres:
    image: postgres:16
    container_name: craftloop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: craftloop_db_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: craftloop_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
